### ISSUE TITLE
PyTIX support for Pimoroni Unicorn pHAT or HAT

### ISSUE THREAD

**Issue by Medalibi** [mdoege/PyTIX#2]
Hi,

Thank you very much for the amazing script. 

Is there any possible future update to support the two new products from Pimoroni; [Unicorn pHAT](https://shop.pimoroni.com/products/unicorn-phat) and [Unicorn HAT](https://shop.pimoroni.com/products/unicorn-hat). I am trying to create something out of the examples scripts provided within its [github Repository](https://github.com/pimoroni/unicorn-hat) and the script you used for the Scroll pHAT.

If you have already started on something please let me know to not reinvent the wheel.

Cheers,
Mo

**Comment by mdoege** [comment]
Hi Mohamed!

You would really have to ask @dglaude about this, as the Pimoroni support has been entirely merged from his fork of PyTIX.

As far as I am concerned, I will merge any improvements that are made, so keep the support for new devices coming. :-)

Hope this helps,
Martin

**Comment by Medalibi** [comment]
Hi,

Thank you for teh quick reply. And I will do.

I am not really a python expert. I will try my best to make something worth be called an improvement.

Thanks,
Mohamed

**Comment by dglaude** [comment]
@Medalibi I have the hardware (both the Unicorn pHAT and HAT) and I should be able to do something... but there is a problem. I had the hardware at the time I worked on my variant of PyTIX, so I guess I did not find a solution to this problem. If you have a suggestion on how to fix it, please speak out and I will see what I can do.

The PyTIX require a minimum of 9 row of LED.
If the time is HhMm then the screen look like this
H.hhh.MM.mmm
H.hhh.MM.mmm
H.hhh.MM.mmm
This is a 3*12 array of LEDs.

Where H can hold values 0, 1 or 2 (3 is available but never needed)
Where h can hold values from 0 to 9.
Where M can hold value from 0 to 5 (6 is available but never needed)
Where m can hold value from 0 to 9.

If you squeeze things, by removing the "space" between digit, you can get this:
HhhhMMmmm
HhhhMMmmm
HhhhMMmmm
This is a 3*9 array of LEDs.

If you can come up with a way to hold all of this information on a 4*8 (Unicorn pHAT) or 8*8 (Unicorn HAT) then I can try to write the code for that, submit it to @mdoege and propose it to @Pimoroni (they already have a lot of my code in the example available on github).

Regards.

**Comment by Medalibi** [comment]
Hi @dglaude

Thank you very much for teh reply. I don't think that there is any hope with the Unicorn pHAT, but there is a possible way to do it with a Unicorn HAT. I am thinking of making the hours on the top: ..H.hhh. or .H..hhh. and the minutes on the bottom: .MM.mmm. Where you can leave a space of one or two lines between the hours and the minutes as showen below:

<img width="384" alt="screen shot 2017-05-24 at 20 30 41" src="https://cloud.githubusercontent.com/assets/5444362/26422213/ddac6a12-40c0-11e7-9c0d-e1448ee26641.png">

<img width="387" alt="screen shot 2017-05-24 at 20 30 26" src="https://cloud.githubusercontent.com/assets/5444362/26422217/e3222946-40c0-11e7-9d97-3e5905cc078e.png">

Apologies about the late reply. It was a busy start of week.

Cheers,
Mo

**Comment by dglaude** [comment]
Hi have a squared curses version of the clock matching your first drawing.
I forced the time to be 23:45 for testing.
I made the unit of the minute to be yellow to distinguish from the ten of
hour.

I will work on the Unicorn HAT latter: https://pinout.xyz/pinout/unicorn_hat
Then likely I will do a Sense HAT version:
https://www.raspberrypi.org/products/sense-hat/

I will likely commit to my fork https://github.com/dglaude/PyTIX
Then submit a Pull request to here.

I am at the beginning of a long week-end, so it should done before next
week... but I don't know when I will have time not AFK.

Regards


2017-05-24 21:42 GMT+02:00 Mohamed <notifications@github.com>:

**Comment by dglaude** [comment]
I made a version for Unicorn HAT from Pimoroni:
https://twitter.com/DavidGlaude/status/867813730121375744

And a version for Sense HAT from the Raspberry Pi Foundation:
https://twitter.com/DavidGlaude/status/867818638816026625

I made a pull request for it.

Regards.

**Comment by dglaude** [comment]
There might be a way for Unicorn pHAT:

```
H h h M M m m m
H h h M M m m m
h h h M M m m m
h h h M M m m m
```

**Comment by Medalibi** [comment]
Thank you very much.

Yes, It can work.

Again thank you.
Mo
